### ISSUE TITLE
Parameters aggregate into doesn't work

### ISSUE THREAD

**Issue by warang580** [FreeAllMedia/mrt#2]
In the README examples, you wrote 

```javascript
this.parameters("thought")
  .aggregate
  .into("thoughts");
```

but actually, this doesn't work (without `.aggregate` as well) : 

```
TypeError: this.parameters(...).aggregate.into is not a function
```
It looks like `.aggregate` works for `parameters()` and `.into()` for `link()` **only**.

Also, these two functions does the same thing on different objects, why not use only one function name for both?

**Comment by dcrockwell** [comment]
`.aggregate` and `.into` don't actually do the same thing. Like you've pointed out, .aggregate is for specifying that a parameter is an array of values. .into is for specifying an array (or object when also using `.usingKey`) for *new links* to be instantiated into.

`parameters` are properties of the object, but don't create new link objects on their own. They are placeholders for values which are returned when you call `.parameters()` without arguments.

``` javascript
class Person {
    // multiple parameters set at once
    this.parameters(
        "favoriteColors",
        "favoriteMeals",
        "favoriteCartoons"
    ).aggregate.multiValue;
}

const person = new Person();

person
    .favoriteColors("blue", "green")
    .favoriteMeals("french fries", "pizza")
    .favoriteCartoons("Mighty Mouse", "Star Trek: The Animated Series");

person.parameters(); // { favoriteColors: ["blue", "green"], favoriteMeals: ["french fries", "pizza"], favoriteCartoons: ["Mighty Mouse", "Star Trek: The Animated Series"];
```

**Comment by dcrockwell** [comment]
I updated the README. If you have a suggestion for a more consistent API, open a new issue for it.
