### ISSUE TITLE
Mrt Promises Issue

### ISSUE THREAD

**Issue by MikeMcMullan** [FreeAllMedia/mrt#3]
Hey D.C,

Ran into a problem involving nodes native Promises library that is being caused by my use of mrt. Another library I am using uses Promise.defer but for some reason mrt is causing it to be undefined.

I have tested this in node v5.6.0 and v5.10.0. To reproduce my problem open a nodejs repl then run Promise.defer, you will see that is a function. If you then require('mrt') then run Promise.defer again you will see it is now undefined. 

I searched this repo for the words 'Promise' and 'defer' and got no results. I have no idea how this could be happening.

**Comment by dcrockwell** [comment]
bizarre! Thanks for the steps to reproduce. I'll look into it now.

**Comment by MikeMcMullan** [comment]
Just figured out the problem, it is being caused by a dependency of a dependency. In this case babel-polyfill which is a dependency of incognito. I'm not even sure what babel-polyfill does. Not sure how to proceed now.

**Comment by dcrockwell** [comment]
Fixed by https://github.com/FreeAllMedia/mrt/pull/4 ?
